version: 2
updates:
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      next:
        patterns:
          - "next*"
      tailwind:
        patterns:
          - "tailwindcss*"
          - "@tailwindcss/*"
      aws-amplify:
        patterns:
          - "aws-amplify"
          - "@aws-amplify/*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
