/**
 * Hey API クライアント生成スクリプト
 *
 * バックエンドの OpenAPI スキーマから TypeScript SDK と TanStack Query hooks を生成する
 *
 * 使用方法:
 *   pnpm run generate   (= tsx scripts/generate.ts)
 *
 * 環境変数:
 *   BACKEND_URL - バックエンド API の URL (デフォルト: http://127.0.0.1:4040)
 */

import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const packageDir = join(__dirname, '..')
const outputDir = join(packageDir, 'src', 'generated')

// バックエンド URL を環境変数から取得（デフォルト: ローカル開発環境）
const backendUrl =
  process.env.BACKEND_URL ?? process.env.NEXT_PUBLIC_BACKEND_PY_URL ?? 'http://127.0.0.1:4040'

async function checkBackendAvailable(): Promise<boolean> {
  try {
    const response = await fetch(`${backendUrl}/healthcheck`, {
      method: 'GET',
      signal: AbortSignal.timeout(5000),
    })
    return response.ok
  } catch {
    return false
  }
}

function createPlaceholderFiles(): void {
  // 出力ディレクトリを作成
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true })
  }

  // プレースホルダーファイルを作成
  const typesContent = `// Auto-generated by @hey-api/openapi-ts
// This is a placeholder file. Run 'pnpm run generate' with backend running to generate actual types.

export type {}
`

  const sdkContent = `// Auto-generated by @hey-api/openapi-ts
// This is a placeholder file. Run 'pnpm run generate' with backend running to generate actual SDK.

export {}
`

  writeFileSync(join(outputDir, 'types.gen.ts'), typesContent)
  writeFileSync(join(outputDir, 'sdk.gen.ts'), sdkContent)
  console.log('   Created placeholder files in src/generated/')
}

async function generate(): Promise<void> {
  console.log('🔍 Checking backend availability...')
  console.log(`   Backend URL: ${backendUrl}`)

  const isAvailable = await checkBackendAvailable()

  if (!isAvailable) {
    console.warn('⚠️  Backend is not available. Skipping client generation.')
    console.warn('   Make sure the backend is running: make run')

    // 既存の生成ファイルがあればそれを使用
    if (existsSync(join(outputDir, 'types.gen.ts'))) {
      console.log('ℹ️  Using existing generated files')
      return
    }

    // 生成ファイルがない場合はプレースホルダーを作成
    console.log('📝 Creating placeholder files')
    createPlaceholderFiles()
    return
  }

  console.log('✅ Backend is available')
  console.log(`🚀 Generating SDK from ${backendUrl}/openapi.json...`)

  try {
    // Hey API CLI を使用して SDK を生成
    execFileSync('pnpm', ['exec', 'openapi-ts'], { stdio: 'inherit' })
    console.log(`✨ Generated SDK in ${outputDir}`)
  } catch (error) {
    console.error('❌ Failed to generate SDK:', error)
    process.exit(1)
  }
}

generate()
